reporting-disabled = true

[meta]
  dir = "/var/lib/influxdb/meta"

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"

[admin]
  enabled = true

[[graphite]]
  enabled = true
  protocol = "tcp"
  templates = [
    "spark-system-stats.streaming.*.*.*.executor.* ..app.framework_id.executor_id..measurement* kind=executor",
    "spark-system-stats.streaming.*.*.*.jvm.* ..app.framework_id.executor_id..measurement* kind=jvm",
    "spark-system-stats.streaming.*.*.driver.* ..app.framework_id..measurement* kind=driver",
    "spark-system-stats.streaming.*.*.driver.jvm.* ..app.framework_id...measurement* kind=driver_jvm",

    #spark-system-stats.streaming.click_persistence.bulk_clicks.4d8c635a-b84b-4ae1-9298-2ef57b785007-0399.8290ed4c-5a5f-41ad-b7c2-c96fee4cb246-S1.executor.filesystem.file.largeRead_ops
    "spark-system-stats.streaming.*.*.*.*.executor.* ..app.app.framework_id.executor_id..measurement* kind=executor",

    "spark-system-stats.streaming.*.*.driver.streaming.*.StreamingMetrics.streaming.* ..app.framework_id......measurement* kind=driver_streaming"
  ]

[[graphite]]
  enabled = true
  protocol = "udp"
  templates = [
    "spark-system-stats.streaming.* ..app.task_id.src.src.measurement*"
  ]
