[template]
src = "config.properties.tmpl"
dest = "/opt/presto/installation/etc/config.properties"

keys = [
  "/presto/include/coordinator",
  "/presto/discovery/enabled",
  "/presto/coordinator/enabled",
  "/presto/http/port",
  "/presto/discovery/uri",
  "/presto/query/maxmemory",
  "/presto/query/maxmemory/pernode",
  "/presto/query/max/age",
  "/presto/query/max/concurrent/queries",
  "/presto/lowmemory/killer/enabled",
  "/presto/task/concurrency",
  "/presto/task/max/worker/threads",
  "/presto/nodescheduler/min/candidates"
]
